// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export {
  AzureKeyCredential } from "@azure/core-auth";
export {
  AzureSearchDocumentsAutocompleteItem as AutocompleteItem,
  AzureSearchDocumentsAutocompleteMode as AutocompleteMode,
  AzureSearchDocumentsAutocompleteResult as AutocompleteResult,
  AzureSearchDocumentsDebugInfo as DebugInfo,
  AzureSearchDocumentsFacetResult as FacetResult,
  AzureSearchDocumentsHybridCountAndFacetMode as HybridCountAndFacetMode,
  AzureSearchDocumentsHybridSearch as HybridSearchOptions,
  AzureSearchDocumentsIndexActionType as IndexActionType,
  AzureSearchDocumentsIndexDocumentsResult as IndexDocumentsResult,
  AzureSearchDocumentsIndexingResult as IndexingResult,
  KnownAzureSearchDocumentsHybridCountAndFacetMode as KnownHybridCountAndFacetMode,
  KnownAzureSearchDocumentsQueryDebugMode as KnownQueryDebugMode,
  KnownAzureSearchDocumentsQueryLanguage as KnownQueryLanguage,
  KnownAzureSearchDocumentsQuerySpellerType as KnownQuerySpeller,
  KnownAzureSearchDocumentsSemanticErrorMode as KnownSemanticErrorMode,
  KnownAzureSearchDocumentsSemanticErrorReason as KnownSemanticErrorReason,
  KnownAzureSearchDocumentsSemanticFieldState as KnownSemanticFieldState,
  KnownAzureSearchDocumentsSemanticQueryRewritesResultType as KnownSemanticQueryRewritesResultType,
  KnownAzureSearchDocumentsSemanticSearchResultsType as KnownSemanticSearchResultsType,
  KnownAzureSearchDocumentsVectorFilterMode as KnownVectorFilterMode,
  KnownAzureSearchDocumentsVectorQueryKind as KnownVectorQueryKind,
  KnownAzureSearchDocumentsVectorThresholdKind as KnownVectorThresholdKind,
  AzureSearchDocumentsQueryAnswerResult as QueryAnswerResult,
  AzureSearchDocumentsQueryCaptionResult as QueryCaptionResult,
  AzureSearchDocumentsQueryDebugMode as QueryDebugMode,
  AzureSearchDocumentsQueryLanguage as QueryLanguage,
  AzureSearchDocumentsQueryResultDocumentInnerHit as QueryResultDocumentInnerHit,
  AzureSearchDocumentsQueryResultDocumentRerankerInput as QueryResultDocumentRerankerInput,
  AzureSearchDocumentsQueryResultDocumentSubscores as QueryResultDocumentSubscores,
  AzureSearchDocumentsQueryRewritesDebugInfo as QueryRewritesDebugInfo,
  AzureSearchDocumentsQueryRewritesValuesDebugInfo as QueryRewritesValuesDebugInfo,
  AzureSearchDocumentsQuerySpellerType as QuerySpeller,
  AzureSearchDocumentsQueryType as QueryType,
  AzureSearchDocumentsScoringStatistics as ScoringStatistics,
  AzureSearchDocumentsSearchMode as SearchMode,
  AzureSearchDocumentsSemanticFieldState as SemanticFieldState,
  AzureSearchDocumentsSemanticQueryRewritesResultType as SemanticQueryRewritesResultType,
  AzureSearchDocumentsSingleVectorFieldResult as SingleVectorFieldResult,
  AzureSearchDocumentsTextResult as TextResult,
  AzureSearchDocumentsVectorsDebugInfo as VectorsDebugInfo
} from "./models/azure/search/documents/index.js";

// TODO: KnowledgeBase exports need to be remapped from old KnowledgeAgent names
// The generated code uses "KnowledgeBase" instead of "KnowledgeAgent" in type names
// Many granular types may have been consolidated or removed
// Need to review what public API should be exposed for knowledge base functionality
/*
export {
  KnowledgeAgentActivityRecord as BaseKnowledgeAgentActivityRecord,
  KnowledgeAgentActivityRecordUnion as KnowledgeAgentActivityRecord,
  KnowledgeAgentAzureBlobActivityArguments,
  KnowledgeAgentAzureBlobActivityRecord,
  KnowledgeAgentAzureBlobReference,
  KnowledgeAgentMessage,
  KnowledgeAgentMessageContent as BaseKnowledgeAgentMessageContent,
  KnowledgeAgentMessageContentUnion as KnowledgeAgentMessageContent,
  KnowledgeAgentMessageImageContent,
  KnowledgeAgentMessageImageContentImage,
  KnowledgeAgentMessageTextContent,
  KnowledgeAgentModelAnswerSynthesisActivityRecord,
  KnowledgeAgentModelQueryPlanningActivityRecord,
  KnowledgeAgentReference as BaseKnowledgeAgentReference,
  KnowledgeAgentReferenceUnion as KnowledgeAgentReference,
  KnowledgeAgentRetrievalActivityRecord as BaseKnowledgeAgentRetrievalActivityRecord,
  KnowledgeAgentRetrievalActivityRecordUnion as KnowledgeAgentRetrievalActivityRecord,
  KnowledgeAgentRetrievalRequest,
  KnowledgeAgentRetrievalResponse,
  KnowledgeAgentSearchIndexActivityArguments,
  KnowledgeAgentSearchIndexActivityRecord,
  KnowledgeAgentSearchIndexReference,
  KnowledgeAgentSemanticRerankerActivityRecord,
  KnowledgeSourceKind,
  KnowledgeSourceParams as BaseKnowledgeSourceParams,
  KnowledgeSourceParamsUnion as KnowledgeSourceParams,
  KnownKnowledgeSourceKind,
  SearchIndexKnowledgeSourceParams,
} from "./models/azure/search/documents/knowledgeBase/index.js";
*/
export {
  AzureSearchDocumentsIndexesAIFoundryModelCatalogName as AIFoundryModelCatalogName,
  AzureSearchDocumentsIndexesAIServicesAccountKey as AIServicesAccountKey,
  AzureSearchDocumentsIndexesAnalyzedTokenInfo as AnalyzedTokenInfo,
  AzureSearchDocumentsIndexesAnalyzeResult as AnalyzeResult,
  AzureSearchDocumentsIndexesAsciiFoldingTokenFilter as AsciiFoldingTokenFilter,
  AzureSearchDocumentsIndexesAzureActiveDirectoryApplicationCredentials as AzureActiveDirectoryApplicationCredentials,
  AzureSearchDocumentsIndexesAzureMachineLearningSkill as AzureMachineLearningSkill,
  AzureSearchDocumentsIndexesAzureOpenAIModelName as AzureOpenAIModelName,
  AzureSearchDocumentsIndexesAzureOpenAITokenizerParameters as AzureOpenAITokenizerParameters,
  AzureSearchDocumentsIndexesBinaryQuantizationCompression as BinaryQuantizationCompression,
  AzureSearchDocumentsIndexesBM25SimilarityAlgorithm as BM25Similarity,
  AzureSearchDocumentsIndexesCharFilter as BaseCharFilter,
  AzureSearchDocumentsIndexesCharFilterName as CharFilterName,
  AzureSearchDocumentsIndexesChatCompletionExtraParametersBehavior as ChatCompletionExtraParametersBehavior,
  AzureSearchDocumentsIndexesChatCompletionResponseFormat as ChatCompletionResponseFormat,
  ChatCompletionResponseFormatJsonSchemaProperties,
  ChatCompletionResponseFormatType,
  AzureSearchDocumentsIndexesChatCompletionSchema as ChatCompletionSchema,
  AzureSearchDocumentsIndexesCjkBigramTokenFilter as CjkBigramTokenFilter,
  CjkBigramTokenFilterScripts,
  AzureSearchDocumentsIndexesClassicSimilarityAlgorithm as ClassicSimilarity,
  AzureSearchDocumentsIndexesClassicTokenizer as ClassicTokenizer,
  AzureSearchDocumentsIndexesCognitiveServicesAccount as BaseCognitiveServicesAccount,
  AzureSearchDocumentsIndexesCognitiveServicesAccountKey as CognitiveServicesAccountKey,
  AzureSearchDocumentsIndexesCommonGramTokenFilter as CommonGramTokenFilter,
  CommonModelParameters,
  AzureSearchDocumentsIndexesConditionalSkill as ConditionalSkill,
  AzureSearchDocumentsIndexesCorsOptions as CorsOptions,
  AzureSearchDocumentsIndexesCustomEntity as CustomEntity,
  CustomEntityAlias,
  AzureSearchDocumentsIndexesCustomNormalizer as CustomNormalizer,
  DataChangeDetectionPolicy as BaseDataChangeDetectionPolicy,
  DataDeletionDetectionPolicy as BaseDataDeletionDetectionPolicy,
  AzureSearchDocumentsIndexesDefaultCognitiveServicesAccount as DefaultCognitiveServicesAccount,
  DictionaryDecompounderTokenFilter,
  AzureSearchDocumentsIndexesDistanceScoringFunction as DistanceScoringFunction,
  DistanceScoringParameters,
  DocumentExtractionSkill,
  DocumentIntelligenceLayoutSkillChunkingProperties,
  DocumentIntelligenceLayoutSkillChunkingUnit,
  DocumentIntelligenceLayoutSkillExtractionOptions,
  DocumentIntelligenceLayoutSkillMarkdownHeaderDepth,
  DocumentIntelligenceLayoutSkillOutputFormat,
  DocumentIntelligenceLayoutSkillOutputMode,
  EdgeNGramTokenFilterSide,
  AzureSearchDocumentsIndexesEdgeNGramTokenizer as EdgeNGramTokenizer,
  ElisionTokenFilter,
  EntityLinkingSkill,
  EntityRecognitionSkillV3,
  AzureSearchDocumentsIndexesFieldMapping as FieldMapping,
  FieldMappingFunction,
  AzureSearchDocumentsIndexesFreshnessScoringFunction as FreshnessScoringFunction,
  FreshnessScoringParameters,
  GetIndexStatsSummaryOptionalParams,
  GetIndexStatsSummaryResponse,
  AzureSearchDocumentsIndexesHighWaterMarkChangeDetectionPolicy as HighWaterMarkChangeDetectionPolicy,
  IndexerExecutionResult,
  IndexerExecutionStatus,
  IndexerExecutionStatusDetail,
  IndexerPermissionOption,
  IndexerResyncOption,
  IndexersResyncOptionalParams,
  IndexerState,
  IndexerStatus,
  IndexingMode,
  AzureSearchDocumentsIndexesIndexingSchedule as IndexingSchedule,
  IndexProjectionMode,
  IndexStatisticsSummary,
  InputFieldMappingEntry,
  KeepTokenFilter,
  KeywordMarkerTokenFilter,
  KnowledgeAgentModel as BaseKnowledgeAgentModel,
  KnowledgeAgentOutputConfiguration,
  KnowledgeAgentOutputConfigurationModality,
  KnowledgeAgentRequestLimits,
  KnowledgeSourceReference,
  KnownAIFoundryModelCatalogName,
  KnownAzureOpenAIModelName,
  KnownBlobIndexerDataToExtract,
  KnownBlobIndexerImageAction,
  KnownBlobIndexerParsingMode,
  KnownBlobIndexerPDFTextRotationAlgorithm,
  KnownChatCompletionExtraParametersBehavior,
  KnownChatCompletionResponseFormatType,
  KnownCustomEntityLookupSkillLanguage,
  KnownDocumentIntelligenceLayoutSkillChunkingUnit,
  KnownDocumentIntelligenceLayoutSkillExtractionOptions,
  KnownDocumentIntelligenceLayoutSkillMarkdownHeaderDepth,
  KnownDocumentIntelligenceLayoutSkillOutputFormat,
  KnownDocumentIntelligenceLayoutSkillOutputMode,
  KnownEntityCategory,
  KnownEntityRecognitionSkillLanguage,
  KnownImageAnalysisSkillLanguage,
  KnownImageDetail,
  KnownIndexerExecutionEnvironment,
  KnownIndexerExecutionStatusDetail,
  KnownIndexerPermissionOption,
  KnownIndexerResyncOption,
  KnownIndexingMode,
  KnownIndexProjectionMode,
  KnownKeyPhraseExtractionSkillLanguage,
  KnownKnowledgeAgentModelKind,
  KnownKnowledgeAgentOutputConfigurationModality,
  KnownLexicalAnalyzerName,
  KnownLexicalNormalizerName,
  KnownLexicalNormalizerName as KnownNormalizerNames,
  KnownMarkdownHeaderDepth,
  KnownMarkdownParsingSubmode,
  KnownOcrLineEnding,
  KnownOcrSkillLanguage,
  KnownPermissionFilter,
  KnownPIIDetectionSkillMaskingMode,
  KnownRankingOrder,
  KnownRegexFlags,
  KnownSearchFieldDataType,
  KnownSearchIndexerDataSourceType,
  KnownSearchIndexPermissionFilterOption,
  KnownSentimentSkillLanguage,
  KnownSplitSkillEncoderModelName,
  KnownSplitSkillLanguage,
  KnownSplitSkillUnit,
  KnownTextSplitMode,
  KnownTextTranslationSkillLanguage,
  KnownVectorEncodingFormat,
  KnownVectorSearchAlgorithmKind,
  KnownVectorSearchAlgorithmMetric,
  KnownVectorSearchCompressionKind,
  KnownVectorSearchCompressionRescoreStorageMethod,
  KnownVectorSearchCompressionTarget,
  KnownVectorSearchVectorizerKind,
  KnownVisualFeature,
  LanguageDetectionSkill,
  LengthTokenFilter,
  AzureSearchDocumentsIndexesLexicalAnalyzer as BaseLexicalAnalyzer,
  LexicalAnalyzerName,
  LexicalNormalizer as BaseLexicalNormalizer,
  LexicalNormalizerName,
  AzureSearchDocumentsIndexesLexicalTokenizer as BaseLexicalTokenizer,
  LexicalTokenizerName,
  LimitTokenFilter,
  ListIndexStatsSummary,
  AzureSearchDocumentsIndexesLuceneStandardAnalyzer as LuceneStandardAnalyzer,
  AzureSearchDocumentsIndexesMagnitudeScoringFunction as MagnitudeScoringFunction,
  MagnitudeScoringParameters,
  AzureSearchDocumentsIndexesMappingCharFilter as MappingCharFilter,
  MarkdownHeaderDepth,
  MarkdownParsingSubmode,
  MergeSkill,
  MicrosoftLanguageStemmingTokenizer,
  MicrosoftLanguageTokenizer,
  MicrosoftStemmingTokenizerLanguage,
  MicrosoftTokenizerLanguage,
  NativeBlobSoftDeleteDeletionDetectionPolicy,
  AzureSearchDocumentsIndexesNGramTokenizer as NGramTokenizer,
  OcrLineEnding,
  OutputFieldMappingEntry,
  PathHierarchyTokenizerV2 as PathHierarchyTokenizer,
  PatternCaptureTokenFilter,
  PatternReplaceCharFilter,
  PatternReplaceTokenFilter,
  PermissionFilter,
  PhoneticEncoder,
  PhoneticTokenFilter,
  RankingOrder,
  RescoringOptions,
  ResourceCounter,
  AzureSearchDocumentsIndexesScalarQuantizationCompression as ScalarQuantizationCompression,
  ScalarQuantizationParameters,
  ScoringFunction as BaseScoringFunction,
  ScoringFunctionAggregation,
  ScoringFunctionInterpolation,
  SearchAlias,
  SearchIndexerDataContainer,
  SearchIndexerDataIdentity as BaseSearchIndexerDataIdentity,
  SearchIndexerDataNoneIdentity,
  SearchIndexerDataUserAssignedIdentity,
  SearchIndexerError,
  SearchIndexerIndexProjectionSelector,
  SearchIndexerKnowledgeStoreBlobProjectionSelector,
  SearchIndexerKnowledgeStoreFileProjectionSelector,
  SearchIndexerKnowledgeStoreObjectProjectionSelector,
  SearchIndexerKnowledgeStoreProjection,
  SearchIndexerKnowledgeStoreProjectionSelector,
  SearchIndexerKnowledgeStoreTableProjectionSelector,
  SearchIndexerLimits,
  SearchIndexerSkill as BaseSearchIndexerSkill,
  SearchIndexerStatus,
  SearchIndexerWarning,
  SearchIndexKnowledgeSourceParameters,
  SearchIndexPermissionFilterOption,
  AzureSearchDocumentsIndexesSemanticConfiguration as SemanticConfiguration,
  SemanticField,
  SemanticPrioritizedFields,
  SemanticSearch,
  SentimentSkillV3,
  ServiceCounters,
  ServiceLimits,
  ShaperSkill,
  ShingleTokenFilter,
  Similarity,
  SnowballTokenFilter,
  SnowballTokenFilterLanguage,
  SoftDeleteColumnDeletionDetectionPolicy,
  SplitSkillEncoderModelName,
  SplitSkillUnit,
  SqlIntegratedChangeTrackingPolicy,
  StemmerOverrideTokenFilter,
  StemmerTokenFilter,
  StemmerTokenFilterLanguage,
  AzureSearchDocumentsIndexesStopAnalyzer as StopAnalyzer,
  StopwordsList,
  StopwordsTokenFilter,
  AzureSearchDocumentsIndexesSearchSuggester as SearchSuggester,
  SynonymTokenFilter,
  AzureSearchDocumentsIndexesTagScoringFunction as TagScoringFunction,
  TagScoringParameters,
  AzureSearchDocumentsIndexesTextWeights as TextWeights,
  TokenCharacterKind,
  AzureSearchDocumentsIndexesTokenFilter as BaseTokenFilter,
  TokenFilterName,
  TruncateTokenFilter,
  AzureSearchDocumentsIndexesUaxUrlEmailTokenizer as UaxUrlEmailTokenizer,
  UniqueTokenFilter,
  AzureSearchDocumentsIndexesVectorEncodingFormat as VectorEncodingFormat,
  AzureSearchDocumentsIndexesVectorSearchCompression as BaseVectorSearchCompression,
  VectorSearchCompressionKind,
  VectorSearchCompressionRescoreStorageMethod,
  VectorSearchCompressionTarget,
  AzureSearchDocumentsIndexesVectorSearchProfile as VectorSearchProfile,
  VectorSearchVectorizerKind,
  AzureSearchDocumentsIndexesWordDelimiterTokenFilter as WordDelimiterTokenFilter,
} from "./models/azure/search/documents/indexes/index.js";
export { default as GeographyPoint } from "./geographyPoint.js";
export { IndexDocumentsBatch } from "./indexDocumentsBatch.js";
export {
  AutocompleteOptions,
  AutocompleteRequest,
  BaseSearchRequestOptions,
  BaseVectorQuery,
  BaseVectorThreshold,
  CountDocumentsOptions,
  DeleteDocumentsOptions,
  DocumentDebugInfo,
  ExcludedODataTypes,
  ExtractDocumentKey,
  ExtractiveQueryAnswer,
  ExtractiveQueryCaption,
  GenerativeQueryRewrites,
  GetDocumentOptions,
  IndexDocumentsAction,
  IndexDocumentsOptions,
  ListSearchResultsPageSettings,
  MergeDocumentsOptions,
  MergeOrUploadDocumentsOptions,
  NarrowedModel,
  QueryAnswer,
  QueryCaption,
  QueryResultDocumentSemanticField,
  QueryRewrites,
  SearchDocumentsPageResult,
  SearchDocumentsResult,
  SearchDocumentsResultBase,
  SearchFieldArray,
  SearchIndexingBufferedSenderDeleteDocumentsOptions,
  SearchIndexingBufferedSenderFlushDocumentsOptions,
  SearchIndexingBufferedSenderMergeDocumentsOptions,
  SearchIndexingBufferedSenderMergeOrUploadDocumentsOptions,
  SearchIndexingBufferedSenderOptions,
  SearchIndexingBufferedSenderUploadDocumentsOptions,
  SearchIterator,
  SearchOptions,
  SearchPick,
  SearchRequestOptions,
  SearchRequestQueryTypeOptions,
  SearchResult,
  SearchScoreThreshold,
  SelectArray,
  SelectFields,
  SemanticDebugInfo,
  SemanticErrorMode,
  SemanticErrorReason,
  SemanticSearchOptions,
  SemanticSearchResultsType,
  SuggestDocumentsResult,
  SuggestNarrowedModel,
  SuggestOptions,
  SuggestRequest,
  SuggestResult,
  UnionToIntersection,
  UploadDocumentsOptions,
  VectorFilterMode,
  VectorizableImageBinaryQuery,
  VectorizableImageUrlQuery,
  VectorizableTextQuery,
  VectorizedQuery,
  VectorQuery,
  VectorQueryKind,
  VectorSearchOptions,
  VectorSimilarityThreshold,
  VectorThreshold,
} from "./indexModels.js";
export { KnowledgeAgent, RetrieveKnowledgeOptions } from "./knowledgeAgentModels.js";
export {
  KnowledgeRetrievalClient,
  KnowledgeRetrievalClientOptions,
} from "./knowledgeRetrievalClient.js";
export { odata } from "./odata.js";
export { KnownSearchAudience } from "./searchAudience.js";
export { SearchClient, SearchClientOptions } from "./searchClient.js";
export { SearchIndexClient, SearchIndexClientOptions } from "./searchIndexClient.js";
export { SearchIndexerClient, SearchIndexerClientOptions } from "./searchIndexerClient.js";
export {
  DEFAULT_BATCH_SIZE,
  DEFAULT_FLUSH_WINDOW,
  DEFAULT_RETRY_COUNT,
  IndexDocumentsClient,
  SearchIndexingBufferedSender,
} from "./searchIndexingBufferedSender.js";
export {
  AIServicesAccountIdentity,
  AIServicesVisionParameters,
  AIServicesVisionVectorizer,
  AliasIterator,
  AnalyzeRequest,
  AnalyzeTextOptions,
  AzureBlobKnowledgeSource,
  AzureBlobKnowledgeSourceParameters,
  AzureMachineLearningVectorizer,
  AzureMachineLearningVectorizerParameters,
  AzureOpenAIEmbeddingSkill,
  AzureOpenAIParameters,
  AzureOpenAIVectorizer,
  BaseAzureMachineLearningVectorizerParameters,
  BaseKnowledgeSource,
  BaseVectorSearchAlgorithmConfiguration,
  BaseVectorSearchVectorizer,
  BlobIndexerDataToExtract,
  BlobIndexerImageAction,
  BlobIndexerParsingMode,
  BlobIndexerPDFTextRotationAlgorithm,
  CharFilter,
  ChatCompletionSkill,
  CognitiveServicesAccount,
  ComplexDataType,
  ComplexField,
  CreateAliasOptions,
  CreateDataSourceConnectionOptions,
  CreateIndexerOptions,
  CreateIndexOptions,
  CreateKnowledgeAgentOptions,
  CreateKnowledgeSourceOptions,
  CreateOrUpdateAliasOptions,
  CreateorUpdateDataSourceConnectionOptions,
  CreateorUpdateIndexerOptions,
  CreateOrUpdateIndexOptions,
  CreateOrUpdateKnowledgeAgentOptions,
  CreateOrUpdateKnowledgeSourceOptions,
  CreateOrUpdateSkillsetOptions,
  CreateOrUpdateSynonymMapOptions,
  CreateSkillsetOptions,
  CreateSynonymMapOptions,
  CustomAnalyzer,
  CustomEntityLookupSkill,
  CustomEntityLookupSkillLanguage,
  DataChangeDetectionPolicy,
  DataDeletionDetectionPolicy,
  DeleteAliasOptions,
  DeleteDataSourceConnectionOptions,
  DeleteIndexerOptions,
  DeleteIndexOptions,
  DeleteKnowledgeAgentOptions,
  DeleteKnowledgeSourceOptions,
  DeleteSkillsetOptions,
  DeleteSynonymMapOptions,
  DocumentIntelligenceLayoutSkill,
  EdgeNGramTokenFilter,
  EntityCategory,
  EntityRecognitionSkill,
  EntityRecognitionSkillLanguage,
  ExhaustiveKnnAlgorithmConfiguration,
  ExhaustiveKnnParameters,
  GetAliasOptions,
  GetDataSourceConnectionOptions,
  GetIndexerOptions,
  GetIndexerStatusOptions,
  GetIndexOptions,
  GetIndexStatisticsOptions,
  GetIndexStatsSummaryOptions,
  GetKnowledgeAgentOptions,
  GetKnowledgeSourceOptions,
  GetServiceStatisticsOptions,
  GetSkillSetOptions,
  GetSynonymMapsOptions,
  HnswAlgorithmConfiguration,
  HnswParameters,
  ImageAnalysisSkill,
  ImageAnalysisSkillLanguage,
  ImageDetail,
  IndexerExecutionEnvironment,
  IndexingParameters,
  IndexingParametersConfiguration,
  IndexIterator,
  IndexNameIterator,
  IndexStatisticsSummaryIterator,
  KeyAuthAzureMachineLearningVectorizerParameters,
  KeyPhraseExtractionSkill,
  KeyPhraseExtractionSkillLanguage,
  KeywordTokenizer,
  KnowledgeAgentAzureOpenAIModel,
  KnowledgeAgentIterator,
  KnowledgeAgentModel,
  KnowledgeSource,
  KnowledgeSourceIterator,
  KnownAnalyzerNames,
  KnownCharFilterNames,
  KnownTokenFilterNames,
  KnownTokenizerNames,
  LexicalAnalyzer,
  LexicalNormalizer,
  LexicalTokenizer,
  ListAliasesOptions,
  ListDataSourceConnectionsOptions,
  ListIndexersOptions,
  ListIndexesOptions,
  ListKnowledgeAgentsOptions,
  ListKnowledgeSourcesOptions,
  ListSkillsetsOptions,
  ListSynonymMapsOptions,
  LuceneStandardTokenizer,
  NGramTokenFilter,
  NoAuthAzureMachineLearningVectorizerParameters,
  OcrSkill,
  OcrSkillLanguage,
  PatternAnalyzer,
  PatternTokenizer,
  PIIDetectionSkill,
  PIIDetectionSkillMaskingMode,
  RegexFlags,
  ResetDocumentsOptions,
  ResetIndexerOptions,
  ResetSkillsOptions,
  RunIndexerOptions,
  ScoringFunction,
  ScoringProfile,
  SearchField,
  SearchFieldDataType,
  SearchIndex,
  SearchIndexAlias,
  SearchIndexer,
  SearchIndexerCache,
  SearchIndexerDataIdentity,
  SearchIndexerDataSourceConnection,
  SearchIndexerDataSourceType,
  SearchIndexerIndexProjection,
  SearchIndexerIndexProjectionParameters,
  SearchIndexerKnowledgeStore,
  SearchIndexerKnowledgeStoreParameters,
  SearchIndexerSkill,
  SearchIndexerSkillset,
  SearchIndexKnowledgeSource,
  SearchIndexStatistics,
  SearchResourceEncryptionKey,
  SearchServiceStatistics,
  SentimentSkill,
  SentimentSkillLanguage,
  SimilarityAlgorithm,
  SimpleField,
  SplitSkill,
  SplitSkillLanguage,
  SynonymMap,
  TextSplitMode,
  TextTranslationSkill,
  TextTranslationSkillLanguage,
  TokenAuthAzureMachineLearningVectorizerParameters,
  TokenFilter,
  VectorSearch,
  VectorSearchAlgorithmConfiguration,
  VectorSearchAlgorithmKind,
  VectorSearchAlgorithmMetric,
  VectorSearchCompression,
  VectorSearchVectorizer,
  VisionVectorizeSkill,
  VisualFeature,
  WebApiParameters,
  WebApiSkill,
  WebApiSkills,
  WebApiVectorizer,
} from "./serviceModels.js";
export { createSynonymMapFromFile } from "./synonymMapHelper.js";
